rootProject.name = "factory"
includeBuild("../logicinterface")
includeBuild("../logic")
includeBuild("../repositoryinterface")
includeBuild("../repository")
includeBuild("../dalinterface")
includeBuild("../dal")
includeBuild("../serviceinterface")
includeBuild("../service")
includeBuild("../model")
