name: Build Gradle Project
on: [push, pull_request]
permissions:
  contents: read
  pull-requests: read
jobs:
  name: Test & Build Project
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run:
        - cd api && ./gradlew test && ../
        - cd dal && ./gradlew test && ../
        - cd logic && ./gradlew test && ../
  build:
    runs-on: ubuntu-latest
    working-directory: ./api
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build