name: Build Gradle Project
on: [push, pull_request]
permissions:
  contents: read
  pull-requests: read
jobs:
  test:
    name: Test Projects
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Test API
        working-directory: ./api
        run: ./gradlew test
      - name: Test DAL
        working-directory: ./dal
        run: ./gradlew test
      - name: Test Logic
        working-directory: ./logic
        run: ./gradlew test
  build:
    name: Build API Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v1
        with:
          java-version: 21
      - name: Build with Gradle
        working-directory: ./api
        run: |
          ./gradlew build